apiVersion: apps/v1
kind: Deployment
metadata: 
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: web-pod
      labels:
        env: production
    spec:
      containers: 
      - name: httpd
        image: 269mehta/webserver-httpd:latest
